<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cardNewReleases</name>
   <tag></tag>
   <elementGuidId>b5a6ea39-6b89-4d96-96ec-bd1c6d971e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ytmusic-grid-renderer[@role='heading']//ytmusic-navigation-button-renderer[1]//button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
