<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>playPauseIcon</name>
   <tag></tag>
   <elementGuidId>a6a24f11-9462-489e-bd3f-1507763c6405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tp-yt-paper-icon-button[@id='play-pause-button']//tp-yt-iron-icon[@id='icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
